#!/bin/bash

# Example: ./ansible_helper play playbooks/deploy.yml -i inventory/dev -e 'some_var=some_value'

mkdir -p $(pwd)/var/log/ansible
mkdir -p $(pwd)/var/tmp

docker run --rm -it \
  -v ~/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
  -v $(pwd)/ansible-playbook:/ansible/playbooks:rw \
  -v $(pwd)/var/log/ansible:/var/log/ansible:rw \
  -v $(pwd)/var/tmp:/tmp:rw \
  sc/ansible-playbook "$@"
