---

- name: This is the inner task example
  hosts: localhost
  gather_facts: no

  vars_files:
    - /ansible/playbooks/example3/somelist.yml

  tasks:
    - name: write vars to file
      shell: echo "{{ it_name }}, {{ it_desc }}" >> /tmp/print_debug.txt

    - debug:
        var: ext_var



