---
- name: This is a hello-world example
  hosts: localhost
  tasks:

    - name: Exec shell command
      shell: ls -lah
      register: shell_result

    - name: Create a file called '/tmp/testfile.txt' with the content of shell_result
      copy:
        content: "{{ shell_result.stdout }}"
        dest: /tmp/testfile.txt
