---
- name: This is a task example
  hosts: localhost

  vars_files:
    - /ansible/playbooks/example3/somelist.yml

  tasks:
          
    - name: create vars file
      shell: echo "vars" > /tmp/print_debug.txt


    - name: call inner playbook
      shell: >
             ansible-playbook print_debug.yml 
             -e "it_name={{ item.name }}"
             -e "it_desc={{ item.description }}" 
             -e "ext_var=abc" 
             -i inventory/local
      args:
        chdir: /ansible/playbooks/example3/inner
      loop: "{{ somelist }}"
      


